#!/bin/bash

current_dir=$(pwd)

ovms_count=$(echo $current_dir | grep -o "OVMS.V3" | wc -l)

if [ $ovms_count -gt 1 ]; then
  echo "Error: More than one OVMS.V3 directory found in the path"
  exit 1
fi

root_dir=$(echo "$current_dir" | sed 's|\(.*OVMS.V3\).*|\1|')
elf="$root_dir/build/ovms3.elf"

for adr in $* ; do
  if [[ "$adr" =~ "elf" ]] ; then
    elf="$adr"
  else
    cmd+=" -ex 'l *${adr/:*/}'"
  fi
done
cmd+=" -ex 'q'"
echo "Using elf file: $elf"
eval xtensa-esp32-elf-gdb -batch $elf $cmd 2>/dev/null 
